name: Release the binary file

on:
  push:
    branches: [ master ]
    tag: 
      - v*

jobs:
  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tag version
        run: echo ::set-output name=tag::${GITHUB_REF##*v}
        id: tag

      - uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.G_H_SECRET }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: ""
          draft: false
          prerelease: false

  release-binary:
    name: Release the binary
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Uploading binary to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: builds/sender application/php
        env:
          GITHUB_TOKEN: ${{ secrets.G_H_SECRET }}